Repository virejdasani/pythOwO, pull requests merged in 2022-06, with the labels that each got.

#2 uwuified readme
  README.md
Labels: documentation

#3 fix typo in weadme
  README.md
Labels: documentation

#4 Oowified source code and example comments
  exwamples/example.pyowo
  pythowo.py
  stwings_with_awwows.py
Labels: uwu/owofication

#5 Update pythowo.py
  pythowo.py
Labels: uwu/owofication

#12 Fixed a minor README.md mistake
  README.md
Labels: documentation

#7 Add capability to run files directly
  README.md
  pythowo.py
Labels: enhancement

#15 Change continue keyword to continuwu
  pythowo.py
Labels: uwu/owofication
